global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


# prometheus --config.file=/Users/sudo/CodeProjects/Other/TradingAlgos/prometheus/prometheus.yml